### PR TITLE
Python plot module updates

### PR DESCRIPTION
**Pull request by rafaeljmoraes**
Hi Geir,

Some updates to the python plot module.

Please check my changes in the README file.

Cheers,

Rafael

### CODE REVIEW

**Review by geirev — APPROVED** [review]

**Comment by geirev** [comment]
I will test the scripts further. I am no python expert and my python environment was messed up but should work now.

**Comment by rafaeljmoraes** [comment]
We could set up some CI on the repository to check if any update breaks anything.

These scripts are very much dependent on how the tecplot files are written. So any changes on them might require updates on the python scripts.

**Comment by geirev** [comment]
Yes, I know, the whole code should have tests.  For now, I am the only one accepting changes so for the Fortran code I have some control. I also thought we were not yet converged on the plotting and model outputs so I went a bit easy on that part.  Your script looks really well coded by the way :-).

**Comment by geirev** [comment]
I can now run your plot.py script by writing
   python3 ../python/enkf_seir/plot/plot.py --data_dir ./
The default dir uses a windows syntax .\\ and that fails on my Linux.

There may be a simple way around this as explained here:
https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

Geir

**Comment by rafaeljmoraes** [comment]
Thanks! I am actually trying to get up to speed with all the new python
capabilities. It's been a while I don't code in python and it's amazing how
the language has evolved.

On this topic, I was taking a look at Camille's jupyter notebook. She has
done very nice job with the bokeh package. I did not know it.

I have spent some time today understanding how some github automated
workflows work and setting up a CI pytest workflow on a private sandbox
gihub repo of mine. It automatically runs all python test after each
pull/pull request. Quite nice...

**Comment by rafaeljmoraes** [comment]
Well spotted! Thanks!

I was also struggling with different python envs on my laptop - it's quite
cumbersome to develop on a laptop you are not admin - and that was delaying
my decision on whether to choose os.path or pathlib.

But the link you sent me has helped me to make up my mind, fix my envs and
choose pathlib. :)

I have also added a first simple unit test for plot.py. It does not
guarantee that changes on the tecplot files will be caught, but at least
covers part of the python code with some QC.

I mentioned that I have been looking into some CI in github. I have added a
workflow to start CI of the python code.

New PR!

**Pull request merged**
