### PR TITLE
Python tests and CI

### PR DESCRIPTION
**Pull request by rafaeljmoraes**
Starting to cover the python code with tests and enabling github workflows to automate tests after pull/PR

### CODE REVIEW

**Review by geirev — APPROVED** [review]
Super Cooool!
Will the tests run automatically on a pull request, or you run them yourself before committing?

**Comment by geirev** [comment]
I tried plot.py again and now it runs like a charm.  

I had to remove the plot. in front of tecplot_loader though
from tecplot_loader import reader as tecplot_reader
from tecplot_loader import available_observations, available_variables,.....

**Comment by rafaeljmoraes** [comment]
Both.

I guess it is a good practice to run the tests before committing. All tests are run by running “py.test” from the root directory. pytest must be installed though - <pip or conda> install pytest.

GitHub should now automatically run the tests every time there is a pull/PR. Let me know if it doesn’t happen automatically in your repository. It does run on mine which I forked from you.

**Comment by rafaeljmoraes** [comment]
Well, so it was not quite like a charm... ;)

python import system sometimes is a pain in the neck... I had to experience many different things to make the tests find the modules both on my local env and in my GitHub repository.

But if it worked for you without the plot in front of it, should work here and in the repo as well.

I will check that and PR a fix.

Cheers!

**Pull request merged**
