### PR TITLE
First python plotting funcitonality

### PR DESCRIPTION
**Pull request by rafaeljmoraes**
Hi Geir,,

This is a first implementation of a ploting capabitity in python using matplotlib. A bit rudimentary at this point, but I am already using to analyse my runs.

Some commits are just experiments with GitHub pages ([https://pages.github.com/](url)). You can cherry-pick only the commits related to the python plotting functionality, but at the end I have reverted all changes realated to the experiments I did. They won't hurt.

More is yet to come! :)

Regards,

Rafael

### CODE REVIEW

**Comment by geirev** [comment]
Very good. Can you do the following:
It seems you have been working directly on the master branch on your local repository.
I have just updated it, so there are some conflicts.
Can you try 
git fetch upstream                     (getting the latest info from upstream)
git rebase upstream/ master    (that will download the latest version and add your changes on top of it)
Then check that all is ok.  Before
git log
git rebase -i 234234referencetoyourfirstcommit23434  (this is the number for the first commit you made)

Then you change pick to squash for all but the latest commit and write one commit message.
If this all works well you just force push

git push --force origin  (which will update the pull request)


Just ask if you have any questions
Thanks
Geir

**Comment by geirev** [comment]
I can also just extract the python catalog and add it in a new commit, but it is a good exercise to do it right from the start.

**Comment by rafaeljmoraes** [comment]
I totally agree this is a good exercise and rather understand how things work here in GitHub than later. Even though I do use git in other projects, this is the very first time I am working with GitHub forks. I am newbie here! 😊 And I really don't get fully get what went wrong.

I also noticed that the conflicts can be resolved here in the website. Would that also be an option?

Thanks for the chance to learn from it.

**Comment by rafaeljmoraes** [comment]
It should be good to go now.

**Review by geirev — APPROVED** [review]
Very nice, thank you

**Pull request merged**
