### PR TITLE
more python test coverage

### PR DESCRIPTION
**Pull request by rafaeljmoraes**
Hi Geir, this PR should fix the problem with the plot.tecplot_reader you found running on your env. All tests run locally (windows, cygwin, ubuntu) and on the automated tests on my forked repository (ubuntu). Cheers, Rafael

### CODE REVIEW

**Review by geirev — APPROVED** [review]

**Comment by geirev** [comment]
Now it worked perfectly. I just changed Hosepi   to Hospi in the tecplot_loader, since this is now also corrected in the m_tecplot.F90

**Comment by rafaeljmoraes** [comment]
Awesome!

I guess the change you mention could be pushed, right? And, unless we come up with some sort of config file that is used to sync those things this type of updates will be necessary.

**Comment by geirev** [comment]
Yes. All done. Now I will watch an episode of casa de papel...😀

Get Outlook for Android<https://aka.ms/ghei36>

[cid:norce_426cc920-64ab-4893-95d0-c29d5dab670c.png]

NORCE Norwegian Research Centre AS
norceresearch.no<https://www.norceresearch.no/>

________________________________

**Comment by rafaeljmoraes** [comment]
Enjoy! Just watched Toy Story with my girls!

**Pull request merged**
